import type { ReportBundle } from '../types/report';
import { Card, SectionTitle } from './ui';

export function QueryWorkbench({ report }: { report: ReportBundle }) {
  const rows = report.queryWorkbench ?? [];
  if (!rows.length) {
    return <Card><SectionTitle eyebrow="Query workbench" title="No canonical query_workbench[] found">Upload a frontend_report_bundle.json generated by the new AIVisibilityAuditor orchestration.</SectionTitle></Card>;
  }
  return (
    <Card><SectionTitle eyebrow="Query workbench" title="Closed-loop query optimisation view">Each query is mapped to owned URLs, top external citations, winning patterns and CMS/PR actions.</SectionTitle>
      <div className="grid gap-4 md:grid-cols-2">
        {rows.map((row) => {
          const vis = row.current_ai_visibility ?? {};
          const mapped = row.mapped_owned_urls ?? [];
          const external = row.external_top3_benchmark ?? [];
          return (
            <article key={row.query_id} className="rounded-2xl border border-slate-200 bg-slate-50 p-4">
              <div className="flex items-start justify-between gap-3">
                <div>
                  <p className="text-xs font-bold uppercase tracking-[0.18em] text-slate-500">{row.query_id} · {row.journey_category || 'Unclassified'}</p>
                  <h3 className="mt-2 text-base font-semibold text-slate-950">{row.query}</h3>
                </div>
                <span className="rounded-full bg-white px-3 py-1 text-xs font-bold text-slate-700">{vis.score ?? 0}/100</span>
              </div>
              <div className="mt-4 grid grid-cols-3 gap-2 text-sm">
                <div><p className="text-slate-500">Status</p><p className="font-semibold text-slate-900">{vis.status || 'n/a'}</p></div>
                <div><p className="text-slate-500">Owned target</p><p className="font-semibold text-slate-900">{vis.owned_target_cited ? 'Yes' : 'No'}</p></div>
                <div><p className="text-slate-500">Competitors</p><p className="font-semibold text-slate-900">{(vis.competitors ?? []).join(', ') || 'None flagged'}</p></div>
              </div>
              <details className="mt-4 rounded-xl bg-white p-3">
                <summary className="cursor-pointer font-semibold text-slate-900">Top mapped owned URLs ({mapped.length})</summary>
                <ol className="mt-2 list-decimal space-y-2 pl-5 text-sm text-slate-700">
                  {mapped.map((item) => <li key={item.url}><span className="font-semibold text-slate-950">{item.title || item.url}</span><br />{item.url}<br />GEO: {item.current_geo_score_120 ?? 0}/120 · gaps: {(item.geo_gaps ?? []).join(', ') || 'none'}</li>)}
                </ol>
              </details>
              <details className="mt-3 rounded-xl bg-white p-3">
                <summary className="cursor-pointer font-semibold text-slate-900">Top external benchmark citations ({external.length})</summary>
                <ol className="mt-2 list-decimal space-y-2 pl-5 text-sm text-slate-700">
                  {external.map((item) => <li key={item.url}>{item.domain || item.url} · {item.sourceType}<br />{item.snippet}</li>)}
                </ol>
              </details>
              <details className="mt-3 rounded-xl bg-white p-3">
                <summary className="cursor-pointer font-semibold text-slate-900">Winning patterns</summary>
                <ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-slate-700">
                  {(row.winning_patterns ?? []).map((p, idx) => <li key={idx}>{p.pattern_type} — {p.owned_content_implication}</li>)}
                </ul>
              </details>
            </article>
          );
        })}
      </div>
    </Card>
  );
}
